options:
  enable-cgroups:
    type: boolean
    default: false
    description: |
       Enable GRUB cgroup overrides cgroup_enable=memory swapaccount=1. WARNING
       changing this option will reboot the host - use with caution on production
       services.
  disable-juju-proxy:
    type: boolean
    default: false
    description: |
      Ignore juju-http(s) proxy settings on this charm.
      If set to true, all juju https proxy settings will be ignored
